### ISSUE TITLE
Feature Request: backup of Followed Artists

### ISSUE THREAD

**Issue by evilsh3ll** [yannickm95/exportify#451]
Hello, can you add the backup of followed artists?

**Comment by yannickm95** [comment]
Hi, how would you see this exactly? Also just a button that downloads a csv with the artist's `ID` and `name` ?

**Comment by evilsh3ll** [comment]
Yes, it seems ok

**Comment by yannickm95** [comment]
I added the functionality and deployed it see #454 for where the find the download button exactly.
